const Images = {
	logoDark_icon: require("@/assets/svg/logoDark.svg"),
	avatar_icon: require("@/assets/svg/avatar.svg"),
	arrowDwn_icon: require("@/assets/svg/arrowDwn.svg"),
	arrowUp_icon: require("@/assets/svg/arrowUp.svg"),
	arrowRight_icon: require("@/assets/svg/arrowRight.svg"),
	bell_icon: require("@/assets/svg/bell.svg"),
	card_icon: require("@/assets/svg/card.svg"),
	cash_icon: require("@/assets/svg/cash.svg"),
	developer: require("@/assets/svg/developer.svg"),
	fx_icon: require("@/assets/svg/fx.svg"),
	getStarted_icon: require("@/assets/svg/getStarted.svg"),
	goBack_icon: require("@/assets/svg/goBack.svg"),
	history_icon: require("@/assets/svg/history.svg"),
	home_icon: require("@/assets/svg/home.svg"),
	minus_icon: require("@/assets/svg/minus.svg"),
	plus_icon: require("@/assets/svg/plus.svg"),
	trendUp_icon: require("@/assets/svg/trendUp.svg"),
	user_icon: require("@/assets/svg/user.svg"),
	x_icon: require("@/assets/svg/x.svg"),
	authBackground_icon: require("@/assets/svg/authBg.svg"),
	fx_illustration: require("@/assets/illustration/fx.svg"),
};

export default Images;
